# Generated by Django 2.1.4 on 2018-12-22 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addressbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressbook',
            name='phone',
            field=models.CharField(max_length=12),
        ),
    ]
